actions = [
			[lock_player],
			[lock_hand_function],
			[cutscene_summon_letterbox],
			[unlock_player_without_control],
			[set_textbox_alignment, [CUTSCENE_TEXTBOX_ALIGNMENT.LOWER_MIDDLE_PORTRAIT_STRETCHED]],
			[send_player_character_relative, [obj_guy, 300,0]],
			[0, cutscene_set_text, ["Finally!"]],
			[send_player_character, [obj_guy, obj_buried_crystal.x, obj_buried_crystal.y - 7]],
			[cutscene_set_text, ["It's just over here.."]],
			[cutscene_set_textbox_player_control, [false]],
			[0, cutscene_wait, [2]],
			[cutscene_set_textbox_player_control, [true]],
			[0, cutscene_wait, [1]],
			[0, cutscene_set_text, ["Hmm.."]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_2x]],
			[0, cutscene_wait, [1]],
			[0, cutscene_set_text, ["It's stuck.."]],
			[shake_obj, [obj_guy, 30]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_3x]],
			[cutscene_set_textbox_player_control, [false]],
			[0, cutscene_wait, [0.5]],
			[cutscene_set_textbox_player_control, [true]],			
			[0, cutscene_set_text, ["Hard!"]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_2x]],
			[0, cutscene_set_text, ["Let's see if I can't shake it loose.."]],
			[cutscene_toggle_portrait_enabled],
			[cutscene_set_textbox_player_control, [false]],
			[cutscene_set_player_state_shaking_loose],
			[0, cutscene_set_text, ["Press Space"]],
			[set_player_state_locked],
			[cutscene_set_textbox_player_control, [false]],
			[cutscene_set_text_noaction, ["STOP RIGHT THERE!!"]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_agape_3]],
			[move_object, [obj_clickable_trigger_cutscene, 238, 292]],
			[0, cutscene_wait, [0.5]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_4_double_take]],
			[0, cutscene_wait, [1]],
			[camera_snap_to_object, [obj_clickable_trigger_cutscene]],
			[0, cutscene_wait, [2]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_5]],
			[cutscene_set_textbox_player_control, [true]],
			[0, cutscene_set_text, ["You thought I wouldn't realize??"]],
			[shake_obj, [obj_clickable_trigger_cutscene, 30]],
			[0, cutscene_set_text, ["You think I'm stupid??"]],
			[shake_obj, [obj_clickable_trigger_cutscene, 30]],
			[0, cutscene_set_text, ["A human guy? With a toad-shaped body?? Looking for the thing???"]],
			[0, cutscene_set_text, ["YOU'RE the guy I'm supposed to trick into destroying the crystal!"]],
			[camera_snap_to_player],
			[cutscene_set_textbox_player_control, [false]],
			[0, cutscene_wait, [1]],
			[cutscene_set_textbox_player_control, [true]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral]],
			[cutscene_toggle_portrait_enabled],
			[0, cutscene_set_text, ["(Toad shaped..)"]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["So you finally figured it out.."]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_2x]],
			[0, cutscene_set_text, ["In that case, I guess I have no choice.."]],
			[cutscene_toggle_textbox_player_control],
			[cutscene_set_text_noaction, ["But to destroy the crystal for yo-AAHGHHGHWHATTHEHELL"]],
			[0, cutscene_wait, [0.5]],
			[spawn_at_obj, [obj_lightning, obj_guy]],
			[set_visible, [obj_buried_crystal]],
			[0, cutscene_wait_frames, [30]],
			[spawn, [obj_flash_fade_out]],
			[hurt_player, [0, 0, 0]],
			[hop, [obj_guy]],
			[animate_obj_x, [obj_guy, 926]],
			[0, cutscene_wait_frames, [10]],
			[change_sprite, [obj_guy, spr_guy_flat_on_face]],
			[0, cutscene_wait, [3]],
			[cutscene_toggle_textbox_player_control],
			[move_object, [obj_clickable_trigger_cutscene, 438, obj_buried_crystal.y - 128]],
			[animate_obj_x, [obj_clickable_trigger_cutscene, obj_buried_crystal.x]],
			[0, cutscene_set_text, ["YOU CAN DO THAT??!?"]],
			[camera_snap_to_object, [obj_clickable_trigger_cutscene]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["You- you betrayed me.. "]],
			[0, cutscene_set_text, ["I told you everything! All my plans!"]],
			[0, cutscene_set_text, ["Do you have any idea how horrible it is to be lied to like this!?"]],
			[cutscene_toggle_portrait_enabled],
			[0, cutscene_set_text, ["Brrrrrring!"]],
			[0, cutscene_set_text, ["Brrrrrring!"]],
			[cutscene_open_second_camera],
			[change_sprite, [obj_guy, spr_guy_flat_on_face_phonecall]],
			[change_sprite, [obj_other_guy_2, spr_other_guy1_on_phone]],
			[0, cutscene_wait_frames, [20]],
			[cutscene_set_text_noaction, ["Dev! Did you manage to obtain the -  AHHHHHHH-"]],
			[0, cutscene_wait_frames, [70]],
			[spawn_at_obj, [obj_lightning, obj_other_guy_2]],
			[0, cutscene_wait_frames, [14]],
			[spawn, [obj_flash_fade_out]],
			[hop, [obj_other_guy_2]],
			[change_sprite, [obj_other_guy_2, spr_other_guy1_shocked]],
			[0, cutscene_wait_frames, [30]],
			[change_sprite, [obj_other_guy_2, spr_other_guy1_shocked_flat]],
			[0, cutscene_wait, [0.5]],
			[cutscene_close_camera2],
			[cutscene_toggle_portrait_enabled],
			[0, cutscene_set_text, ["NOT NOW."]],
			[set_camera_offset, [CAMERA_OFFSET.MIDDLE]],
			[animate_cam_zoom, [0.5]],
			[0, cutscene_set_text, ["What am I supposed to do now?!"]],
			[0, cutscene_set_text, ["If I let you go, you're just gonna escape.."]],
			[0, cutscene_set_text, ["But if I kill you, Master will just get sealed away anyway!"]],
			[0, cutscene_set_text, ["The only way permanently open the rift in time and space is if you're somehow stupid enough to destroy the crystal anyway, DESPITE KNOWING MY PLAN."]],
			[camera_snap_to_player],
			[cutscene_set_portrait, [spr_portrait_guy_neutral]],
			[0, cutscene_set_text, ["..."]],
			[change_sprite, [obj_guy, spr_guy_with_hat]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[flip_playerchar],
			[0, cutscene_set_text, ["Well.. I'm afraid you don't get to decide.."]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["H-Huh?!"]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["If you thought I came here alone, you were dead wrong.."]],
			//[animate_cam_zoom, [0.3]],
			[0, cutscene_set_text, ["Look behind you!"]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[camera_snap_to_object, [obj_clickable_trigger_cutscene]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_agape_0]],
			[0, cutscene_set_text, ["Eh??"]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_agape_3]],
			[0, cutscene_set_text, ["No, NO. That's a lie!!"]],
			[0, cutscene_set_text, ["You want me to turn around, so you can make a dash for the crystal!!"]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["How can I make a dash for the crystal?"]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_agape_1]],
			[0, cutscene_set_text, ["My legs are broken!"]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_agape_3]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["Prove it!!"]],
			[camera_snap_to_player],
			[reset_shake, [obj_guy]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral]],
			[0, cutscene_set_text, ["..."]],
			[0, cutscene_wait, [0.5]],
			[shake_obj, [obj_guy, 30]],
			[0, cutscene_wait_frames, [10]],
			// little pause then a shake
			[change_sprite, [obj_guy, spr_guy_flat_on_face]],
			[0, cutscene_wait_frames, [30]],
			[camera_snap_to_object, [obj_clickable_trigger_cutscene]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_agape_0]],
			[0, cutscene_set_text, ["S-So they are.."]],
			
			[camera_snap_to_player],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["Maybe.."]],
			[0, cutscene_set_text, ["But even so.."]],
			[0, cutscene_set_text, ["It's over.."]],
			[0, cutscene_set_text, ["WE have you beat!"]],
			
			[camera_snap_to_object, [obj_clickable_trigger_cutscene]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["Wha- Wh- DAMMIT!"]],
			[0, cutscene_set_text, ["WHO'S WE??"]],
			[0, cutscene_set_text, ["..."]],
			[shake_obj, [obj_clickable_trigger_cutscene, 30]],
			[0, cutscene_set_text, ["AAAAAAAAAAAAARGH."]],
			[0, cutscene_set_text, ["I'M NOT DOING IT."]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_agape_3]],
			[0, cutscene_set_text, ["I'M NOT GOING TO TURN AROUND.."]],
			[0, cutscene_set_text, ["..."]],
			[cutscene_toggle_textbox_player_control],
			[switch_sprite, [obj_clickable_trigger_cutscene, spr_signpost_angry_front_to_back]],
			[queue_animation_change, [obj_clickable_trigger_cutscene, spr_signpost_back]],
			[cutscene_wait_frames, [15]],
			[camera_snap_to_player],
			[spawn_at_obj, [obj_pickup_crystal, obj_buried_crystal, -30]],	
			[unlock_player_without_control],
			[set_player_state_idle],
			[send_player_character, [obj_guy, obj_buried_crystal.x - 30, obj_buried_crystal.y - 7]],
			[0, cutscene_wait_frames, [90]],
			[shake_obj, [obj_clickable_trigger_cutscene, 15]],
			[cutscene_toggle_portrait_enabled],
			[cutscene_set_text_noaction, ["DAMN IT! WAIT!!"]],
			[0, cutscene_wait, [0.6]],
			[spawn_at_obj, [obj_lightning, obj_guy]],
			[0, cutscene_wait_frames, [20]],
			[flash_to_room, [rm_feature_test2, 60, 30, c_white, snd_buythefield_dramatic_synth]],
			[0, cutscene_wait, [5]],
			[cutscene_dismiss_letterbox],
			[destroy_cutscene_gui],
			[camera_snap_to_player],
			[unlock_hand_function],
			[unlock_player],
			[set_player_state_idle],
			];