actions = [
			[lock_player],
			[lock_hand_function],
			[cutscene_summon_letterbox],
			[unlock_player_without_control],
			[send_player_character_relative, [obj_guy, 0, -300]],
			[set_textbox_alignment, [CUTSCENE_TEXTBOX_ALIGNMENT.LOWER_MIDDLE_PORTRAIT]],
			[0, cutscene_set_text, ["Ughh.."]],
			[0, cutscene_set_text, ["That was a lot less fun than I anticipated."]],
			[0, cutscene_set_text, ["Pretty miserable, actually."]],
			[0, cutscene_set_text, [".. Oh hey!"]],
			[lock_player],
			[camera_snap_to_object, [obj_buried_crystal]],
			[0, cutscene_wait, [1]],
			[0, cutscene_set_text, ["At least I made it to the crystal."]],
			[0, cutscene_set_text, ["If I pick it up before that sign catches wise, I might be able to slip away without any trouble."]],
			[0, cutscene_set_text, [".. Actually, could he even do anything?"]],
			[camera_snap_to_player],
			[0, cutscene_set_text, ["Whatever, just get the gem man!"]],
			[unlock_player_without_control],
			[cutscene_toggle_textbox_player_control],
			[send_player_character_relative, [obj_guy, 0, -300]],
			[0, cutscene_wait, [1.7]],
			[cutscene_toggle_textbox_player_control],
			[move_object, [obj_clickable_trigger_cutscene, obj_guy_standin.x, room_height - 696]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_idle]],
			[lock_player],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[spawn_floaty_text_over_obj, [obj_guy, "BAAAH!", -120]],
			[change_sprite, [obj_guy, spr_guy_knockback]],
			[shake_obj, [obj_guy, 20]],
			[0, cutscene_set_text, ["ARE YOU SURE THAT'S A GOOD IDEA?"]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["What????"]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["Are you sure that's a good idea?"]],
			[change_sprite, [obj_guy, spr_guy_look_north]],
			[0, cutscene_set_text, ["..."]],
			[shake_obj, [obj_clickable_trigger_cutscene, 15]],
			[0, cutscene_set_text, ["You don't see ~anything~ in the way??"]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["Uh.. No. I don't."]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["..."]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_sideeye_happy]],
			[0, cutscene_set_text, ["Okayyyy."]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_smug]],
			[animate_obj_x, [obj_clickable_trigger_cutscene, obj_guy_standin.x + 200]],
			[cutscene_wait, [1]],
			// move him 
			[0, cutscene_set_text, ["You may pass."]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[change_sprite, [obj_guy, spr_guy_with_hat]],
			[0, cutscene_set_text, ["Is there something I should be aware of?"]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["..."]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_sideeye_happy]],
			[0, cutscene_set_text, ["I don't know.."]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_smug]],
			[0, cutscene_set_text, ["..."]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[camera_snap_id, ["detour"]],
			[0, cutscene_set_text, ["Well, there is a detour to the west.."]],
			[cutscene_wait, [1]],
			[0, cutscene_set_text, ["Maybe I'll just take that instead."]],
			[camera_snap_to_player],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_sideeye_happy]],
			[0, cutscene_set_text, ["Why?"]],
			[0, cutscene_set_text, ["If there's a perfectly good path here to your feeble human eyes, why not go ahead and take it?"]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral]],
			[cutscene_dismiss_letterbox],
			[0, cutscene_set_text, ["..."]],
			[set_textbox_alignment, [CUTSCENE_TEXTBOX_ALIGNMENT.LOWER_MIDDLE_PORTRAIT_STRETCHED]],
			[0, cutscene_set_text, ["(There's definitely something I'm not seeing this way..)"]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_sideeye_happy]],
			[destroy_cutscene_gui],
			[camera_snap_to_player],
			[unlock_hand_function],
			[unlock_player],];