actions = [
			[lock_player],
			[lock_hand_function],
			[cutscene_summon_letterbox],
			[unlock_player_without_control],
			[set_textbox_alignment, [CUTSCENE_TEXTBOX_ALIGNMENT.LOWER_MIDDLE_PORTRAIT_STRETCHED]],
			[send_player_character_relative, [obj_guy, 300,0]],
			[0, cutscene_set_text, ["Finally!"]],
			[send_player_character, [obj_guy, obj_buried_crystal.x, obj_buried_crystal.y - 7]],
			[cutscene_set_text, ["It's just over here.."]],
			[cutscene_set_textbox_player_control, [false]],
			[0, cutscene_wait, [2]],
			[cutscene_set_textbox_player_control, [true]],
			[0, cutscene_wait, [1]],
			[0, cutscene_set_text, ["Hmm.."]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_2x]],
			[0, cutscene_wait, [1]],
			[0, cutscene_set_text, ["It's stuck.."]],
			[shake_obj, [obj_guy, 30]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_3x]],
			[cutscene_set_textbox_player_control, [false]],
			[0, cutscene_wait, [0.5]],
			[cutscene_set_textbox_player_control, [true]],
			[0, cutscene_set_text, ["Hard!"]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_2x]],
			[0, cutscene_set_text, ["Let's see if I can't shake it loose.."]],
			[cutscene_toggle_portrait_enabled],
			[cutscene_set_textbox_player_control, [false]],
			[cutscene_set_player_state_shaking_loose],
			[0, cutscene_set_text, ["Press Space"]],
			[set_player_state_locked],
			[cutscene_set_textbox_player_control, [false]],
			[cutscene_set_text_noaction, ["STOP RIGHT THERE!!"]],
			[change_sprite, [obj_clickable_trigger_cutscene, spr_signpost_agape_3]],
			[move_object, [obj_clickable_trigger_cutscene, 238, 292]],
			[0, cutscene_wait, [0.5]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_4_double_take]],
			[0, cutscene_wait, [1]],
			[camera_snap_to_object, [obj_clickable_trigger_cutscene]],
			[0, cutscene_wait, [2]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_5]],
			[cutscene_set_textbox_player_control, [true]],
			[0, cutscene_set_text, ["You thought I wouldn't realize??"]],
			[shake_obj, [obj_clickable_trigger_cutscene, 30]],
			[0, cutscene_set_text, ["You think I'm stupid??"]],
			[shake_obj, [obj_clickable_trigger_cutscene, 30]],
			[0, cutscene_set_text, ["A human guy? With a toad-shaped body?? Looking for the thing???"]],
			[0, cutscene_set_text, ["YOU'RE the guy I'm supposed to trick into destroying the crystal!"]],
			[camera_snap_to_player],
			[cutscene_set_textbox_player_control, [false]],
			[0, cutscene_wait, [1]],
			[cutscene_set_textbox_player_control, [true]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral]],
			[cutscene_toggle_portrait_enabled],
			[0, cutscene_set_text, ["(Toad shaped..)"]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["So you finally figured it out.."]],
			[change_sprite, [obj_guy, spr_guy_grab_crystal_2x]],
			[0, cutscene_set_text, ["In that case, I guess I have no choice.."]],
			[cutscene_toggle_textbox_player_control],
			[cutscene_set_text_noaction, ["But to destroy the crystal for yo-AAHGHHGHWHATTHEHELL"]],
			[0, cutscene_wait, [0.5]],
			[spawn_at_obj, [obj_lightning, obj_guy]],
			[set_visible, [obj_buried_crystal]],
			[0, cutscene_wait_frames, [30]],
			[hurt_player, [0, 0, 0]],
			[hop, [obj_guy]],
			[animate_obj_x, [obj_guy, 926]],
			[0, cutscene_wait_frames, [10]],
			
			[change_sprite, [obj_guy, spr_guy_flat_on_face]],
			[0, cutscene_wait, [3]],
			[cutscene_toggle_textbox_player_control],
			[move_object, [obj_clickable_trigger_cutscene, 438, obj_buried_crystal.y - 128]],
			[animate_obj_x, [obj_clickable_trigger_cutscene, obj_buried_crystal.x]],
			[0, cutscene_set_text, ["YOU CAN DO THAT??!?"]],
			[camera_snap_to_object, [obj_clickable_trigger_cutscene]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["You- you betrayed me.. "]],
			[0, cutscene_set_text, ["I told you everything! All my plans!"]],
			[0, cutscene_set_text, ["Do you have any idea how horrible it is to have no-one you can trust!"]],
			[cutscene_dismiss_letterbox],
			[destroy_cutscene_gui],
			[camera_snap_to_player],
			[unlock_hand_function],
			[unlock_player],];