#macro FRAME_RATE 60
#macro ROOM_START rm_level_select

#macro DEBUG_GENERAL true

#macro DEBUG_COLLISIONS false
#macro RESOLUTION_W 1024
#macro RESOLUTION_H 768
#macro SCREEN_MIDDLE RESOLUTION_H/2
#macro SCREEN_CENTER RESOLUTION_W/2

#macro TILE_SIZE 64

#macro Z_LEVEL_DEPTH_DIFFERENCE 240