dialogue_array = array_create(3, 0);

var _intro = [
	[cutscene_enter],
	[audio_play_sound, [snd_ow, 0, false]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [obj_guy, spr_guy_flat_on_face]],
	[delay, [45, shake_obj, [obj_guy, 15]]],
	[delay, [45, switch_sprite, [obj_guy, spr_guy_knockback]]],
	[0, cutscene_set_text, ["WAKE UP WAKE UP WAKE UP WAKE UUUUP!!!!!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[set_player_state_idle],
	[send_player_character_relative, [obj_guy, 30, 0]],
	[0, cutscene_set_text, ["Gah! What the hell?"]],
	[send_player_character_relative, [obj_guy, -30, 0]],
	[0, cutscene_set_text, ["W-Where am I??"]],
	[switch_sprite, [me, spr_signpost_smug]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[turn_player_toward_object, [me]],
	[camera_snap_to_object, [me]],
	[0, cutscene_set_text, ["Ha, Are you serious?& \nYou really can't remember?"]],
	[switch_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["It's a tech demo and stuff!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[camera_snap_to_object, [obj_guy]],
	[send_player_character, [obj_guy, 1232, 800]],
	[0, cutscene_set_text, ["Tech demo.;.;.; \nNot a real demo?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["No,; that was two months ago and it sucked."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Did it?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["The gameplay did.& Alas!"]],
	[switch_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["The good thing about good work though, is that the can be repurposed for a fun little, little, little,; little adventure,; with a proper arpg setup."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I'm so exhausted. Is this thing gonna take a while?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_agape_3]],
	[shake_obj, [me, 15]],
	[0, cutscene_set_text, ["How many littles do I need to use!?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Okay, okay!; \nGive me a break,; I just woke up."]],
	[0, cutscene_set_text, ["So,; what's the object of this adventure?& \nDo I have to rescue a princess?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Bro what?"]],
	[switch_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["How covetous."]],
	[switch_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Your mission,; should you choose to accept it,; is thusly:"]],
	[0, cutscene_set_text, ["1.& Discover Unburied Treasure& \n2.& Find and Open The Rainbow Door \n3.& Use; A Cell Phone"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, [";.;.;. That's it?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_agape_3]],
	[0, cutscene_set_text, ["I don't want to hear it!& \nGo forth already!!; Go Forth!!"]],
	[increment_dialogue, [me]],
	[switch_sprite, [me, sprite_idle]],
	[npc_reset_sprite, [me]],
	[cutscene_exit],
];

var _response1 = [
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I opened the chest."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_smug]],
	[0, cutscene_set_text, ["Good! Have you retrieved the vibes?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["The vibes disappeared.."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_frog_eyes_2]],
	[0, cutscene_set_text, ["Haha, you FOOL!"]],
	[shake_obj, [me, 30]],
	[0, cutscene_set_text, ["Of course they did! Everyone knows you're not supposed to expose vibes to oxygen!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["Damn."]],
	[switch_sprite, [me, spr_signpost_idle]],
];

var _response2 = [
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["I went through the rainbow door."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Woah! Where'd it take you??"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, [";.;.;.; Back here."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[cutscene_wait_frames, [30]],
	[switch_sprite, [me, spr_signpost_idle_4]],
	[0, cutscene_set_text, ["Is that it??"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["Yeah."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_idle_fried]],
	[0, cutscene_set_text, ["Man, this game sucks."]],
];

var _response3 = [
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I found and used the cell phone."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["Who did you call???"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, [".&.&.&"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Actually,& someone called me."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Yes?????"]],
	[switch_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["And who was it?????"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, [".;.;.;"]],
	[switch_sprite, [me, spr_signpost_highlight]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I suppose& I can only wonder.;.;."]],
	[switch_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["One thing's for certain.;."]],
	[shake_obj, [me, 5]],
	[switch_sprite, [me, spr_signpost_agape_0]],
	[0, cutscene_set_text, ["It was probably the ugliest,; nastiest,; screeching voice I've ever heard."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_agape_1]],
	[0, cutscene_set_text, ["..."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Like an animal or something."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_idle_fried]],
	[0, cutscene_set_text, ["L- let's just move on.."]],
	[0, cutscene_set_text, ["..."]],
	[shake_obj, [me, 15]],
	[switch_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Okay!"]],
];

var _response_nothing_new = [
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Nothing yet.."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Go forth, my son, and conquer."]],
];

var _response_incomplete_bookend = [[0, cutscene_set_text, ["Talk to me when you've done more."]]];

var _response_all_junk_completed = [
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Well I'll be.;.;"]],
	[0, cutscene_set_text, ["You did it!& \nYou actually did it!"]],
	[0, cutscene_set_text, ["You fulfilled all three of my IMPOSSIBLE TASKS."]],
	[switch_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["Now what did we learn from this fantastic experience??"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I wasted a year of my life floundering in gamemaker?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[shake_obj, [me, 15]],
	[switch_sprite, [me, spr_signpost_agape_3]],
	[0, cutscene_set_text, ["SIX MONTHS!!& \nMORE LIKE SIX MONTHS!"]],
	[switch_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["And let us not forget the freshly christened technical knowhow a project like this confers!"]],
	[switch_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Well I reckon there's plenty new object oriented tricks up your sleeve.;."]],
	[0, cutscene_set_text, ["Quick!& Use the ~Strategy Pattern~"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["&.&.&.&"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["&.&.&.&"]],
	[switch_sprite, [me, spr_signpost_stressed]],
	[0, cutscene_set_text, [";Unemployable."]],
	[cutscene_set_portrait, [spr_portrait_guy_angry]],
	[0, cutscene_set_text, ["Pop it open and take a look! I made this stuff super extendable."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[shake_obj, [me, 15]],
	[switch_sprite, [me, spr_signpost_agape_3]],
	[0, cutscene_set_text, ["I can't read!& \nBut thanks for rubbing that in my face!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["So what now?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[switch_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Easy!"]],
	[fade_in_obj, [obj_key, 848, 720, 180]],
	[0, cutscene_set_text, ["Just take this key and complete the level."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["There are levels??"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Probably not!"]],
	[0, cutscene_set_text, ["But the functionality's there, so we might as well show it off."]],
	[0, cutscene_set_text, ["Goodbye my friend, and remember.;.;.; uh."]],
	[0, cutscene_set_text, ["Don't do drugs!"]],
	[increment_dialogue, [me]],
];

dialogue_array[0] = _intro;

dialogue_array[1] = [
	[cutscene_enter],
	[switch_sprite, [me, sprite_talking]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[audio_play_sound, [snd_ow, 0, false]],
	[turn_player_toward_object, [me]],
	[0, cutscene_set_text, ["How's progress??"]],
	[c_insert_if_true, [npc_check_quest, [me, "q_open_chest"], _response1]], // BUG Array isn't unwrapped before passed as a variable!!!!  *RESOLVED* (but not well)
	[c_insert_if_true, [npc_check_quest, [me, "q_rainbow_door"], _response2]],
	[c_insert_if_true, [npc_check_quest, [me, "q_use_phone"], _response3]],
	[c_insert_if_true, [no_condition_first, [["q_open_chest", "q_rainbow_door", "q_use_phone"], me], _response_nothing_new]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[c_insert_if_true, [multi_condition_false, [["q_open_chest", "q_rainbow_door", "q_use_phone"]], _response_incomplete_bookend]],
	[c_insert_if_true, [multi_condition, [["q_open_chest", "q_rainbow_door", "q_use_phone"]], _response_all_junk_completed]],
	[update_conditions, [me]],
	[switch_sprite, [me, sprite_idle]],
	[npc_reset_sprite, [me]],
	[cutscene_exit],
];
//
dialogue_array[2] = [
	[cutscene_enter],
	[audio_play_sound, [snd_ow, 0, false]],
	[switch_sprite, [me, sprite_talking]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[turn_player_toward_object, [me]],
	[0, cutscene_set_text, ["Are you doing drugs?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["No."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Goodbye!"]],
	[switch_sprite, [me, sprite_idle]],
	[npc_reset_sprite, [me]],
	[cutscene_exit],
];

event_register_script("level_started", self, on_interact);