sprite_index = spr_signpost_back;
sprite_highlight = spr_signpost_back_highlight;
sprite_idle = spr_signpost_back;
on_mouse_enter_args = [self, sprite_highlight];
on_mouse_exit_args = [self, sprite_idle];

dialogue_array = array_create(2, []);

dialogue_array[0] = [
	[lock_player],
	[lock_hand_function],
	[camera_snap_to_object, [me]],
	//[cutscene_summon_letterbox],
	[cutscene_set_portrait_enabled, [false]],
	[0, cutscene_set_text, ["Fun fact! These colorful things are gates."]],
	[0, cutscene_set_text, ["If you find a nearby lever, you can open and close gates of the same color!"]],
	[cutscene_set_portrait_enabled, [true]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["Hmm. Interesting."]],
	[switch_sprite, [me, spr_signpost_back_to_front]],
	[queue_animation_change, [me, spr_signpost_idle]],
	[change_sprite, [obj_guy, spr_guy_knockback]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[shake_obj, [obj_guy, 15]],
	[0, cutscene_set_text, ["What's it say??"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["What the!?"]],
	[change_sprite, [obj_guy, spr_guy_look_north]],
	[0, cutscene_set_text, ["Wh- who are you?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Not important! What's written on the back of me?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Just some useful information about color-coded gates.."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["That's boring."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I found it helpful."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["You look like the most boring person I've ever seen."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Oh.."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["But perfect!!"]],
	[0, cutscene_set_text, ["It's the perfect disguise..."]],
	[change_sprite, [me, spr_signpost_evil_eyes]],
	[0, cutscene_set_text, ["For my TRAP."]],
	[change_sprite, [me, spr_signpost_frog_eyes]],
	[0, cutscene_set_text, ["You see, I am not actually an inanimate object."]],
	[change_sprite, [me, spr_signpost_frog_eyes_2]],
	[0, cutscene_set_text, ["But a construct of darkness! A being of pure evil!!"]],
	[change_sprite, [me, spr_signpost_smug]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["I have obviously been sent to the human world in the form of their most trusted possession of religious signficance."]],
	[0, cutscene_set_text, ["And I will use that trust against them! To lead them astray!"]],
	[0, cutscene_set_text, ["Pretty cool, no?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Why are you telling me this?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Why not?"]],
	[0, cutscene_set_text, ["Now buzz off, I'm waiting for someone important."]],
	[camera_snap_to_player],
	[set_clickable_sprites, [me, spr_signpost_idle, spr_signpost_highlight]],
	[increment_dialogue, [me]],
	[destroy_cutscene_gui],
	[unlock_hand_function],
	[unlock_player],
]; 
dialogue_array[1] = [[lock_player],
			[lock_hand_function],
			[camera_snap_to_object, [me]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["What are you still doing here?"]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["Just thinking.."]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral]], // Make text speed slower?? Would be funny
			[0, cutscene_set_text, ["(I have to find a lever of the same color to open this gate in front of me..)"]],
			[cutscene_set_portrait, [spr_portrait_sign]],
			[0, cutscene_set_text, ["Wow, what a spectacle."]],
			[0, cutscene_set_text, ["I see genius at work."]],
			[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
			[0, cutscene_set_text, ["You'd be surprised."]],
			[0, cutscene_set_text, ["And then disappointed.. Eventually."]],
			[destroy_cutscene_gui],
			[camera_snap_to_player],
			[unlock_hand_function],
			[unlock_player],];
