dialogue_array[0] = [
	[cutscene_enter],
	[turn_player_toward_object, [me]],
	[cutscene_toggle_portrait_enabled],
	[0, cutscene_set_text, ["My Child!"]],
	[cutscene_toggle_portrait_enabled],
	[0, cutscene_set_text, ["Can you move out of the way??"]],
	[0, cutscene_set_text, ["I need to demo how room states can be saved and loaded without breaking anything."]],
	[cutscene_toggle_portrait_enabled],
	[0, cutscene_set_text, ["Oh!"]],
	[0, cutscene_set_text, [";.;.;."]],
	[0, cutscene_set_text, ["But they can't though.."]],
	[cutscene_toggle_portrait_enabled],
	[shake_obj, [me, 30]],
	[cutscene_set_portrait, [spr_portrait_guy_angry]],
	[0, cutscene_set_text, ["Shut up! Just go! We'll fix in post!"]],
	[cutscene_toggle_portrait_enabled],
	[0, cutscene_set_text, ["Okokok! One second.."]],
	[audio_play_sound, [snd_teleport, 0, false]],
	[spawn, [obj_flash_fade_out]],
	[clickable_set_enabled, [instance_by_name, ["whitedoor"]]],
	[instance_destroy, [me]],
	[cutscene_exit],
]

/*
[cutscene_toggle_portrait_enabled],
	[turn_player_toward_object, [me]],
	[0, cutscene_set_text, ["My Child!"]],
	[cutscene_toggle_portrait_enabled],
	[0, cutscene_set_text, ["Can you move out of the way??"]],
	[0, cutscene_set_text, ["I need to demo how room states can be saved and loaded without breaking anything."]],
	[cutscene_toggle_portrait_enabled],
	[0, cutscene_set_text, ["Oh!"]],
	[0, cutscene_set_text, ["..."]],
	[0, cutscene_set_text, ["But they don't though.."]],
	[cutscene_toggle_portrait_enabled],
	[shake_obj, [me, 30]],
	[cutscene_set_portrait, [spr_portrait_guy_angry]],
	[0, cutscene_set_text, ["Shut up! Just go! We'll fix in post!"]],
	[cutscene_toggle_portrait_enabled],
	[0, cutscene_set_text, ["Okokok! One second.."]],
	[spawn, [obj_flash_fade_out]],
	
	[instance_destroy, [me]],