dialogue_array = array_create(3, []);
//var _sign = self;
dialogue_array[0] = [
	[lock_player],
	[lock_hand_function],
	[camera_snap_to_object, [me]],
	[animate_cam_zoom, [1]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Hey hows it going."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["You perked up quick.."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Why wouldn't I?"]],
	[change_sprite, [me, spr_signpost_smug]],
	[0, cutscene_set_text, ["I now have the very best resources at my disposal."]],
	[change_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["A new pair of hands, and feet.."]],
	[change_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["I'll be honest, when I was put in this form without hands or feet, I wasn't really sure how I was going to be able do anything."]],
	[change_sprite, [me, spr_signpost_frog_eyes]],
	[0, cutscene_set_text, ["But, as it turns out one's charm is worth a million more than hands and feet. And arms and legs."]],
	[0, cutscene_set_text, ["Because you can just trick a million more handed-feeted-armmed-legged creatures to do your bidding!"]],
	[change_sprite, [me, spr_signpost_smug]],
	[0, cutscene_set_text, ["I understand now that I am quite a powerful construct."]],
	[shake_obj, [me, 15]],
	[change_sprite, [me, spr_signpost_frog_eyes_2]],
	[0, cutscene_set_text, ["Possibly even the most powerful dark construct of them all!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["About that.."]],
	[0, cutscene_set_text, ["How many dark constructs are there? Will we be seeing more along the way?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["No idea, more of us are fashioned every day."]],
	[0, cutscene_set_text, ["Most of us are waiting for the rift in time and space to grow larger, so we can flood in and start taking things apart."]],
	[0, cutscene_set_text, ["But if I do my job correctly, we won't have to see any of them on our way to the crystal."]],
	[0, cutscene_set_text, ["And none of them can steal my spotlight!!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Good.. good.."]],
	[0, cutscene_set_text, ["Too many cooks and whatnot.. They might get in the way of us getting in the way."]],
	/*
	[camera_snap_to_player],
	[0, cutscene_set_text, ["We meet again."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["?"]],
	[cutscene_set_portrait, [spr_sign_portrait]],
	[0, cutscene_set_text, ["I never thought I'd see you here, you limey sonavagun."]],
	[0, cutscene_set_text, ["I thought you died."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["..."]],
	[cutscene_set_portrait, [spr_sign_portrait]],
	[0, cutscene_set_text, ["I thought I buried you in a dusty grave. That you'd never hurt anyone again."]],
	[0, cutscene_set_text, ["I was wrong."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Why are you following me?"]],
	[camera_snap_to_object, [me]],
	[cutscene_set_portrait, [spr_sign_portrait]],
	[0, cutscene_set_text, ["Answers aren't allocated to dirt like you."]],
	[0, cutscene_set_text, ["Your goop would get all over them. The mud and juices would taint and corrupt Truth."]],
	[0, cutscene_set_text, ["Truth itself would be cast down upon contact with your kind, you.. you jerk."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["..."]],
	[cutscene_set_portrait, [spr_sign_portrait]],
	[0, cutscene_set_text, ["Toad. You're a toad."]],
	[0, cutscene_set_text, ["I didn't have a good word for it before, but you're toadmaxxing hard right now and it's plain to see."]],
	[camera_snap_to_object, [obj_guy]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Could you please turn around so I can read whats on the back of you."]],
	[0, cutscene_set_text, ["I'm very interested in what these buttons are for."]],
	[cutscene_set_portrait, [spr_sign_portrait]],
	[0, cutscene_set_text, ["If you're so interested just press em."]],
	[0, cutscene_set_text, ["I'm not stopping you."]],
	*/
	[increment_dialogue, [me]],
	[destroy_cutscene_gui],
	[camera_snap_to_player],
	[unlock_hand_function],
	[unlock_player],
]; // Set in creation code

// I gotta find a better way of setting them up successively, seeing as this whole instance_by_id thing is unruly and doesn't work so well.
// I saw a tutorial where a dude used scripts for each character and just switched out the scripts to make the thing work.
// That seems like a better way of doing things, but harder to keep track of.
// But I cann do that by changing the clickable script and maybe adding variables to the object.

dialogue_array[1] = [
	[lock_player],
	[lock_hand_function],
	[camera_snap_to_object, [me]],
	[animate_cam_zoom, [1]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Mind giving me a hint?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["A hint! For this??"]],
	[change_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["I suppose we are behind schedule.."]],
	[change_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Well, some of the levers you need to flip are hidden behind the walls of these buildings."]],
	[0, cutscene_set_text, ["It was a form of security system that the contractors were building as they went along."]],
	[0, cutscene_set_text, ["Which is why it's so confusing and nonsensical."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["How do you know this?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [me, spr_signpost_smug]],
	[0, cutscene_set_text, ["Ha! Did you think this form was just for show?"]],
	[0, cutscene_set_text, ["I happen to know the contents of every sign in a three mile radius."]], //??
	[0, cutscene_set_text, ["It allows me to camoflauge myself into ANY environment."]], // flip
	[change_sprite, [me, spr_signpost_highlight]],
	[change_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["As long as I'm facing away from whatever's in front of me.."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["..."]],
	[0, cutscene_set_text, ["So if someone gets to the other side of you.."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [me, spr_signpost_side_eye_stressed]],
	[0, cutscene_set_text, ["Y-Yes, I suppose if there were two observers on either side, I would be caught."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["But also if I walked to the other side.. You would have to stay facing me, no? Or I could just see your face?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [me, spr_signpost_agape_3]],
	[0, cutscene_set_text, ["S-So its a little suspicious that a pitch black sign is rotating to face you wherever you go.."]],
	[0, cutscene_set_text, ["So what?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Good point.."]], // fair enough??
	[0, cutscene_set_text, ["So what happens to the original sign. Are you standing in front of it?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["No."]],
	[change_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["I absorbed it."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Oh, wow.."]],
	[0, cutscene_set_text, ["But, you can only do that for signs?"]],
	[change_sprite, [me, spr_signpost_idle]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["No."]],
	[0, cutscene_set_text, ["Technically I can do it to anything touching me. Including this whole dock.."]],
	[change_sprite, [me, spr_signpost_sideeye_happy]],
	[0, cutscene_set_text, ["But clearly, I was made for espionage. And that would break the whole operation."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [me, spr_signpost_idle]],
	[0, cutscene_set_text, ["Clearly.."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [me, spr_signpost_stressed]],
	[shake_obj, [me, 15]],
	[unlock_player],
	[send_player_character_relative, [obj_guy, 0, 30]],
	[0, cutscene_set_text, ["H-Hey no need to nudge backwards, I don't bite!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["(You're supposed to..)"]],
	[send_player_character_relative, [obj_guy, 0, -15]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Sorry, there's a pebble in my shoe."]],
	[lock_player],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Oh.."]],
	[0, cutscene_set_text, ["..."]],
	[0, cutscene_set_text, ["Why not just absorb it?"]],
	[destroy_cutscene_gui],
	[camera_snap_to_player],
	[unlock_hand_function],
	[unlock_player],
];

dialogue_array[2] = [
	[lock_player],
	[lock_hand_function],
	[camera_snap_to_object, [me]],
	[animate_cam_zoom, [1]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [me, spr_signpost_smug]],
	[0, cutscene_set_text, ["I suppose you want me to tell you what those colorful buttons are for.."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["After pressing them?"]],
	[0, cutscene_set_text, ["I already know what they do. They blow up the nearby barricades of the same color."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [me, spr_signpost_agape_1]],
	[shake_obj, [me, 15]],
	[0, cutscene_set_text, ["Agh-"]],
	[0, cutscene_set_text, ["So you're smarter than you look.."]],
	[change_sprite, [me, spr_signpost_frog_eyes]],
	[shake_obj, [me, 15]],
	[0, cutscene_set_text, ["But did you know! That once you destroy them, those barricades.. are gone FOREVER???"]],
	[change_sprite, [me, spr_signpost_evil_eyes]],
	[0, cutscene_set_text, ["They never come back!!"]],
	[change_sprite, [me, spr_signpost_frog_eyes]],
	[0, cutscene_set_text, ["How does it feel human, to have taken a life with your own hands??"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[change_sprite, [me, spr_signpost_smug]],
	[0, cutscene_set_text, ["What?"]],
	[0, cutscene_set_text, ["Barricades aren't alive."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[queue_animation_change, [me, spr_signpost_idle]], // or wait it out with a timer??
	[0, cutscene_set_text, ["..."]],
	[change_sprite, [me, spr_signpost_stressed]],
	[0, cutscene_set_text, ["They aren't?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["No."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Yes they are!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["No, they aren't."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Huh..."]],
	[0, cutscene_set_text, ["I guess I'm just confused about this whole life thing."]],
	[0, cutscene_set_text, ["I mean- I'm not alive."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["You aren't?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Of course not!!"]],
	[0, cutscene_set_text, ["I'm made of dark energy."]],
	[0, cutscene_set_text, ["How would that make any sense?"]],
	[0, cutscene_set_text, ["B-But you're alive, correct?"]],
	[0, cutscene_set_text, ["I have that part right?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I'm alive."]],
	[0, cutscene_set_text, ["Just dead inside."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Aaaaaghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhha."]],
	[0, cutscene_set_text, ["Drama queen..."]],
	/*
	[0, cutscene_set_text, ["AaaauuuuaaaAAAUUGHHHHHHHH"]],
	[0, cutscene_set_text, ["THATS NOT THE QUESTION!"]],
	//[0, cutscene_set_text, ["Ahhh, I can't believe I'm stuck with such a drama queen for a partner!"]],
	[0, cutscene_set_text, ["Why couldn't I have been made as a dragon! Or some kind of swimming creature!"]],
	[0, cutscene_set_text, ["Instead all I do is stand around giving orders!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I have orders?"]],
	[cutscene_set_portrait, [spr_sign_portrait]],
	[0, cutscene_set_text, ["YES: Do my bidding! Find the Green Lever!!"]],
	[0, cutscene_set_text, ["Go Go Go!!"]],
	[0, cutscene_set_text, ["Everytime I talk to you you give me a headache.."]],
	*/
	[destroy_cutscene_gui],
	[camera_snap_to_player],
	[unlock_hand_function],
	[unlock_player],
];