var _sign = instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1");
actions = [
	//[instance_destroy, [instance_find(obj_clickable_trigger_cutscene, 0)]],
	[lock_player],
	[lock_hand_function],
	[cutscene_set_portrait_enabled, [false]],
	[change_sprite, [instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1"), spr_signpost_stressed]],
	[0, cutscene_set_text, ["WAIT WAIT WAIT-"]],
	[0, cutscene_set_text, ["COME BACK!"]],
	[0, cutscene_wait, [0.2]],
	[unlock_player],
	[cutscene_set_textbox_player_control, [false]],
	[send_player_character, [obj_guy, 2976, 1184]],
	[0, cutscene_wait, [0.3]],
	[camera_snap_to_object, [instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1")]],
	[0, cutscene_wait, [0.8]],
	[lock_player],
	[change_sprite, [obj_guy, spr_guy_look_north]],
	[0, cutscene_wait, [1]],
	[cutscene_set_textbox_player_control, [true]],
	[cutscene_set_portrait_enabled, [true]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Are you the guy??"]],
	[cutscene_set_textbox_player_control, [true]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["..."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["No."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1"), spr_signpost_exhale]],
	[queue_animation_change, [instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1"), spr_signpost_idle_fried]],
	[0, cutscene_set_text, ["Thank god."]],
	[change_sprite, [instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1"), spr_signpost_side_eye_stressed]],
	[0, cutscene_set_text, ["Have you seen him??"]],
	[0, cutscene_set_text, ["Because I'm supposed to run into him, like, RIGHT now."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral]],
	[0, cutscene_set_text, ["..."]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Come to think of it.. I did see someone pass by just a minute ago."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1"), spr_signpost_agape_0]],
	[0, cutscene_set_text, ["Y-you did?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["He said he was looking for something called the Eye Of Convergence?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1"), spr_signpost_agape_1]],
	[shake_obj, [_sign, 15]],
	[0, cutscene_set_text, ["Oh no!"]],
	[0, cutscene_set_text, ["That's what I'm supposed to stop him from reaching!"]],
	[0, cutscene_set_text, ["B-but how'd he get through all these puzzles?!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["He said he knew a shortcut through all these puzzles."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[change_sprite, [instance_by_name(obj_clickable_trigger_cutscene, "dock_sign1"), spr_signpost_agape_2]],
	[shake_obj, [_sign, 15]],
	[0, cutscene_set_text, ["OH NO!"]],
	[shake_obj, [_sign, 45]],
	[0, cutscene_set_text, ["NO NO NO!"]],
	[0, cutscene_set_text, ["This is really bad!!"]],
	[0, cutscene_set_text, ["I gotta catch up with him!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Fat chance of that.."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Eh??"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["Apparently, I'm the only one who can see him."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["WHAT? WHY?"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["I dunno."]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["YOU GOTTA HELP ME."]],
	[0, cutscene_set_text, ["If he gets to the eye before me-"]],
	[0, cutscene_set_text, ["The hole in time and space can be patched up!"]],
	[change_sprite, [_sign, spr_signpost_agape_3]],
	[shake_obj, [_sign, 45]],
	[0, cutscene_set_text, ["And my master will be sealed away again!!"]],
	[cutscene_set_portrait, [spr_portrait_guy_neutral_talking]],
	[0, cutscene_set_text, ["That's terrible.."]],
	[0, cutscene_set_text, ["Which way is the crystal?"]],
	[cutscene_set_portrait, [spr_portrait_sign]],
	[0, cutscene_set_text, ["Right ahead! We just have to get through these stupid easy lever puzzles."]],
	[0, cutscene_set_text, ["Come on!"]],
	[animate_obj_x, [_sign, _sign.x + 1000]],
	[cutscene_toggle_textbox_player_control],
	[camera_snap_to_player],
	[destroy_cutscene_gui],
	[unlock_hand_function],
	[unlock_player],
	[0, cutscene_wait, [2]],
	[instance_destroy, [_sign]],
	
	
	]